server:
  port: 1001
spring:
  datasource:
    url: jdbc:mysql://39.107.141.90:3306/VARIETY_ DISHES?serverTimeZone=UTC&characterEncoding=utf-8
    username: root
    password: Acs574939#
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto